// Cards — composed surfaces: product card and testimonial/quote card.
// Children use flow layout inside a flex surface, so the whole card places
// like any single element.

import { node } from "../../scene/model"
import { registerAll } from "./registry"
import type { ComponentDef } from "./types"
import { FLOW, bodyText, cardSurface, flexCenter, photoPlaceholder } from "./util"

const DEFS: ComponentDef[] = [
  {
    id: "card-product",
    name: "Product Card",
    group: "Cards",
    blurb: "photo + name + price + mini CTA on an elevated surface",
    roles: ["group", "image", "price", "cta"],
    tokensUsed: [
      "--border",
      "--radius",
      "--shadow",
      "--space",
      "--ink",
      "--accent",
      "--accent-2",
      "--primary",
      "--primary-foreground",
      "--font-body",
      "--font-heading",
    ],
    slots: [
      { key: "name", label: "Product name", sample: "Velvet Night Serum" },
      { key: "price", label: "Price", sample: "$49" },
      { key: "cta", label: "CTA label", sample: "Add to bag" },
    ],
    preview: { w: 620, h: 860 },
    build: ({ content, layout, image }) =>
      node({
        id: "surface",
        role: "group",
        layout,
        css: { ...cardSurface, width: "460px" },
        children: [
          node({
            id: "photo",
            role: "image",
            image,
            imageFit: "cover",
            layout: FLOW,
            css: {
              width: "100%",
              height: "360px",
              borderRadius: "calc(var(--radius) * 0.75)",
              overflow: "hidden",
              ...(image ? {} : photoPlaceholder),
            },
          }),
          node({
            id: "name",
            html: content.name,
            editable: true,
            layout: FLOW,
            css: { ...bodyText, fontSize: "32px", fontWeight: "700" },
          }),
          node({
            id: "price",
            role: "price",
            html: content.price,
            editable: true,
            layout: FLOW,
            css: {
              ...bodyText,
              fontFamily: "var(--font-heading)",
              fontSize: "40px",
              fontWeight: "700",
              color: "var(--accent)",
            },
          }),
          node({
            id: "cta",
            role: "cta",
            html: content.cta,
            editable: true,
            layout: FLOW,
            css: {
              ...flexCenter,
              alignSelf: "flex-start",
              background: "var(--primary)",
              color: "var(--primary-foreground)",
              fontFamily: "var(--font-body)",
              fontWeight: "700",
              fontSize: "26px",
              lineHeight: "1",
              padding: "calc(var(--space) * 1.1) calc(var(--space) * 2.4)",
              borderRadius: "var(--radius)",
              whiteSpace: "nowrap",
            },
          }),
        ],
      }),
  },
  {
    id: "card-testimonial",
    name: "Testimonial Card",
    group: "Cards",
    blurb: "customer quote with attribution on an elevated surface",
    roles: ["group", "meta"],
    tokensUsed: [
      "--border",
      "--radius",
      "--shadow",
      "--space",
      "--ink",
      "--accent",
      "--muted",
      "--font-body",
      "--font-heading",
    ],
    slots: [
      {
        key: "quote",
        label: "Quote",
        sample: "The only serum that actually kept its promise.",
      },
      { key: "name", label: "Name", sample: "Maya R." },
      { key: "role", label: "Role", sample: "Verified buyer" },
    ],
    preview: { w: 820, h: 560 },
    build: ({ content, layout }) =>
      node({
        id: "surface",
        role: "group",
        layout,
        css: { ...cardSurface, width: "640px" },
        children: [
          node({
            id: "quotemark",
            html: "“",
            layout: FLOW,
            css: {
              fontFamily: "var(--font-heading)",
              fontSize: "110px",
              lineHeight: "0.6",
              color: "var(--accent)",
              margin: "0",
              marginTop: "calc(var(--space) * 0.5)",
            },
          }),
          node({
            id: "quote",
            html: content.quote,
            editable: true,
            layout: FLOW,
            css: {
              ...bodyText,
              fontFamily: "var(--font-heading)",
              fontSize: "40px",
              lineHeight: "1.3",
            },
          }),
          node({
            id: "attribution",
            role: "meta",
            html: `<strong>${content.name}</strong> · ${content.role}`,
            editable: true,
            layout: FLOW,
            css: {
              ...bodyText,
              fontSize: "26px",
              color: "var(--muted)",
            },
          }),
        ],
      }),
  },
  {
    id: "card-pricing",
    name: "Pricing Card",
    group: "Cards",
    blurb: "tier + big price + brand-bulleted features + CTA",
    roles: ["group", "eyebrow", "price", "meta", "cta"],
    tokensUsed: [
      "--border",
      "--radius",
      "--shadow",
      "--space",
      "--ink",
      "--muted",
      "--accent",
      "--primary",
      "--primary-foreground",
      "--font-body",
      "--font-heading",
    ],
    slots: [
      { key: "tier", label: "Tier", sample: "Pro" },
      { key: "price", label: "Price", sample: "$29" },
      { key: "period", label: "Period", sample: "/month" },
      {
        key: "features",
        label: "Features (one per line)",
        sample: "Unlimited exports\nAll brand kits\nPriority support",
      },
      { key: "cta", label: "CTA label", sample: "Start free trial" },
    ],
    preview: { w: 640, h: 940 },
    build: ({ content, layout }) => {
      const features = content.features
        .split("\n")
        .map((l) => l.trim())
        .filter(Boolean)
        .map(
          (l) =>
            `<li style="display:flex; align-items:baseline; gap:calc(var(--space) * 0.7)"><span style="color:var(--accent); font-weight:800; flex-shrink:0">✓</span><span>${l}</span></li>`
        )
        .join("")
      return node({
        id: "surface",
        role: "group",
        layout,
        css: { ...cardSurface, width: "460px" },
        children: [
          node({
            id: "tier",
            role: "eyebrow",
            html: content.tier,
            editable: true,
            layout: FLOW,
            css: {
              ...bodyText,
              fontSize: "26px",
              fontWeight: "700",
              letterSpacing: "0.24em",
              textTransform: "uppercase",
              color: "var(--accent)",
            },
          }),
          node({
            id: "price",
            role: "price",
            html: `${content.price}<span style="font-size:0.35em; font-weight:600; color:var(--muted)"> ${content.period}</span>`,
            editable: true,
            layout: FLOW,
            css: {
              ...bodyText,
              fontFamily: "var(--font-heading)",
              fontSize: "96px",
              fontWeight: "700",
              lineHeight: "1",
            },
          }),
          node({
            id: "features",
            role: "meta",
            html: `<ul style="list-style:none; margin:0; padding:0; display:flex; flex-direction:column; gap:calc(var(--space) * 0.7)">${features}</ul>`,
            editable: true,
            layout: FLOW,
            css: { ...bodyText, fontSize: "27px", lineHeight: "1.35" },
          }),
          node({
            id: "cta",
            role: "cta",
            html: content.cta,
            editable: true,
            layout: FLOW,
            css: {
              ...flexCenter,
              background: "var(--primary)",
              color: "var(--primary-foreground)",
              fontFamily: "var(--font-body)",
              fontWeight: "700",
              fontSize: "28px",
              lineHeight: "1",
              padding: "calc(var(--space) * 1.2) calc(var(--space) * 2)",
              borderRadius: "var(--radius)",
              whiteSpace: "nowrap",
            },
          }),
        ],
      })
    },
  },
  {
    id: "card-glass",
    name: "Glass Panel",
    group: "Cards",
    blurb: "frosted translucent content panel that floats over photos",
    roles: ["group", "headline", "subhead"],
    tokensUsed: [
      "--border",
      "--radius",
      "--shadow",
      "--space",
      "--ink",
      "--font-heading",
      "--font-body",
    ],
    slots: [
      { key: "title", label: "Title", sample: "Golden hour, bottled" },
      {
        key: "text",
        label: "Text",
        sample: "A warm amber blend for evenings that should last longer.",
      },
    ],
    preview: { w: 860, h: 560 },
    build: ({ content, layout }) =>
      node({
        id: "surface",
        role: "group",
        layout,
        allowOverlap: true,
        css: {
          display: "flex",
          flexDirection: "column",
          gap: "calc(var(--space) * 0.9)",
          width: "620px",
          padding: "calc(var(--space) * 2.2)",
          background: "rgba(255,255,255,0.1)",
          backgroundImage:
            "linear-gradient(180deg, rgba(255,255,255,0.14), rgba(255,255,255,0.02))",
          border: "1px solid var(--border)",
          borderRadius: "var(--radius)",
          boxShadow: "var(--shadow)",
        },
        children: [
          node({
            id: "title",
            role: "headline",
            html: content.title,
            editable: true,
            layout: FLOW,
            css: {
              ...bodyText,
              fontFamily: "var(--font-heading)",
              fontSize: "52px",
              fontWeight: "700",
              lineHeight: "1.1",
            },
          }),
          node({
            id: "text",
            role: "subhead",
            html: content.text,
            editable: true,
            layout: FLOW,
            css: {
              ...bodyText,
              fontSize: "28px",
              lineHeight: "1.45",
              opacity: "0.85",
            },
          }),
        ],
      }),
  },
  {
    id: "card-ticket",
    name: "Ticket",
    group: "Cards",
    blurb: "event ticket with a perforated stub and barcode",
    roles: ["group", "headline", "meta"],
    tokensUsed: [
      "--border",
      "--radius",
      "--shadow",
      "--space",
      "--ink",
      "--accent",
      "--muted",
      "--font-heading",
      "--font-body",
    ],
    slots: [
      { key: "date", label: "Date", sample: "JUN 21" },
      { key: "title", label: "Title", sample: "Neon Nights Live" },
      { key: "meta", label: "Meta", sample: "Doors 8PM · Hall A · Row 12" },
    ],
    preview: { w: 980, h: 420 },
    build: ({ content, layout }) =>
      node({
        id: "surface",
        role: "group",
        layout,
        css: {
          display: "flex",
          alignItems: "stretch",
          width: "760px",
          background: "rgba(255,255,255,0.07)",
          border: "1px solid var(--border)",
          borderRadius: "var(--radius)",
          boxShadow: "var(--shadow)",
          overflow: "hidden",
        },
        children: [
          node({
            id: "stub",
            layout: FLOW,
            css: {
              ...flexCenter,
              flexDirection: "column",
              gap: "calc(var(--space) * 0.4)",
              padding: "calc(var(--space) * 1.6)",
              borderRight: "3px dashed var(--border)",
              background: "rgba(255,255,255,0.05)",
            },
            children: [
              node({
                id: "date",
                role: "meta",
                html: content.date,
                editable: true,
                layout: FLOW,
                css: {
                  ...bodyText,
                  fontFamily: "var(--font-heading)",
                  fontSize: "44px",
                  fontWeight: "800",
                  color: "var(--accent)",
                  whiteSpace: "nowrap",
                },
              }),
              node({
                id: "admit",
                html: "ADMIT ONE",
                layout: FLOW,
                css: {
                  ...bodyText,
                  fontSize: "18px",
                  fontWeight: "700",
                  letterSpacing: "0.22em",
                  color: "var(--muted)",
                },
              }),
            ],
          }),
          node({
            id: "body",
            layout: FLOW,
            css: {
              display: "flex",
              flexDirection: "column",
              justifyContent: "center",
              gap: "calc(var(--space) * 0.6)",
              padding: "calc(var(--space) * 1.6)",
              flex: "1",
            },
            children: [
              node({
                id: "title",
                role: "headline",
                html: content.title,
                editable: true,
                layout: FLOW,
                css: {
                  ...bodyText,
                  fontFamily: "var(--font-heading)",
                  fontSize: "44px",
                  fontWeight: "700",
                  lineHeight: "1.05",
                },
              }),
              node({
                id: "meta",
                role: "meta",
                html: content.meta,
                editable: true,
                layout: FLOW,
                css: { ...bodyText, fontSize: "24px", color: "var(--muted)" },
              }),
              node({
                id: "barcode",
                layout: FLOW,
                css: {
                  height: "34px",
                  width: "240px",
                  backgroundImage:
                    "repeating-linear-gradient(90deg, var(--ink) 0 3px, transparent 3px 7px, var(--ink) 7px 9px, transparent 9px 14px)",
                  opacity: "0.8",
                },
              }),
            ],
          }),
        ],
      }),
  },
  {
    id: "card-polaroid",
    name: "Polaroid",
    group: "Cards",
    blurb: "instant-photo frame with a handwritten caption",
    roles: ["group", "image", "meta"],
    tokensUsed: ["--primary", "--accent", "--accent-2", "--font-heading", "--space"],
    slots: [{ key: "caption", label: "Caption", sample: "summer '26" }],
    variants: [
      {
        key: "tilt",
        label: "Tilt",
        def: "tilted",
        options: [
          { id: "straight", label: "Straight" },
          { id: "tilted", label: "Tilted", css: { rotate: "-4deg" } },
        ],
      },
    ],
    preview: { w: 640, h: 800 },
    build: ({ content, layout, image }) =>
      node({
        id: "surface",
        role: "group",
        layout,
        allowOverlap: true,
        css: {
          display: "flex",
          flexDirection: "column",
          gap: "calc(var(--space) * 1)",
          width: "420px",
          padding: "22px 22px 26px",
          background: "#fdfcf8",
          boxShadow: "0 30px 70px rgba(0,0,0,0.45)",
        },
        children: [
          node({
            id: "photo",
            role: "image",
            image,
            imageFit: "cover",
            layout: FLOW,
            css: {
              width: "100%",
              height: "370px",
              ...(image ? {} : photoPlaceholder),
            },
          }),
          node({
            id: "caption",
            role: "meta",
            html: content.caption,
            editable: true,
            layout: FLOW,
            css: {
              fontFamily: "var(--font-heading)",
              fontStyle: "italic",
              fontSize: "34px",
              textAlign: "center",
              color: "#2b2620",
              margin: "0",
            },
          }),
        ],
      }),
  },
  {
    id: "card-split",
    name: "Split Card",
    group: "Cards",
    blurb: "half photo, half content — compact feature/offer block",
    roles: ["group", "image", "eyebrow", "headline"],
    tokensUsed: [
      "--border",
      "--radius",
      "--shadow",
      "--space",
      "--ink",
      "--accent",
      "--accent-2",
      "--primary",
      "--font-heading",
      "--font-body",
    ],
    slots: [
      { key: "eyebrow", label: "Eyebrow", sample: "New arrival" },
      { key: "title", label: "Title", sample: "The Atlas Tote" },
    ],
    preview: { w: 1000, h: 480 },
    build: ({ content, layout, image }) =>
      node({
        id: "surface",
        role: "group",
        layout,
        css: {
          display: "flex",
          alignItems: "stretch",
          width: "760px",
          background: "rgba(255,255,255,0.06)",
          border: "1px solid var(--border)",
          borderRadius: "var(--radius)",
          boxShadow: "var(--shadow)",
          overflow: "hidden",
        },
        children: [
          node({
            id: "photo",
            role: "image",
            image,
            imageFit: "cover",
            layout: FLOW,
            css: {
              width: "46%",
              minHeight: "320px",
              ...(image ? {} : photoPlaceholder),
            },
          }),
          node({
            id: "content",
            layout: FLOW,
            css: {
              display: "flex",
              flexDirection: "column",
              justifyContent: "center",
              gap: "calc(var(--space) * 0.8)",
              padding: "calc(var(--space) * 2)",
              flex: "1",
            },
            children: [
              node({
                id: "eyebrow",
                role: "eyebrow",
                html: content.eyebrow,
                editable: true,
                layout: FLOW,
                css: {
                  ...bodyText,
                  fontSize: "22px",
                  fontWeight: "700",
                  letterSpacing: "0.26em",
                  textTransform: "uppercase",
                  color: "var(--accent)",
                },
              }),
              node({
                id: "title",
                role: "headline",
                html: content.title,
                editable: true,
                layout: FLOW,
                css: {
                  ...bodyText,
                  fontFamily: "var(--font-heading)",
                  fontSize: "48px",
                  fontWeight: "700",
                  lineHeight: "1.08",
                },
              }),
            ],
          }),
        ],
      }),
  },
]

registerAll(DEFS)
