/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EditorProjectIdRouteImport } from './routes/editor.$projectId'
import { Route as DevEngineRouteImport } from './routes/dev.engine'
import { Route as DevEffectsRouteImport } from './routes/dev.effects'
import { Route as ApiAgentRouteImport } from './routes/api.agent'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorProjectIdRoute = EditorProjectIdRouteImport.update({
  id: '/editor/$projectId',
  path: '/editor/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const DevEngineRoute = DevEngineRouteImport.update({
  id: '/dev/engine',
  path: '/dev/engine',
  getParentRoute: () => rootRouteImport,
} as any)
const DevEffectsRoute = DevEffectsRouteImport.update({
  id: '/dev/effects',
  path: '/dev/effects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentRoute = ApiAgentRouteImport.update({
  id: '/api/agent',
  path: '/api/agent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/agent': typeof ApiAgentRoute
  '/dev/effects': typeof DevEffectsRoute
  '/dev/engine': typeof DevEngineRoute
  '/editor/$projectId': typeof EditorProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/agent': typeof ApiAgentRoute
  '/dev/effects': typeof DevEffectsRoute
  '/dev/engine': typeof DevEngineRoute
  '/editor/$projectId': typeof EditorProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/agent': typeof ApiAgentRoute
  '/dev/effects': typeof DevEffectsRoute
  '/dev/engine': typeof DevEngineRoute
  '/editor/$projectId': typeof EditorProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/api/agent' | '/dev/effects' | '/dev/engine' | '/editor/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/agent' | '/dev/effects' | '/dev/engine' | '/editor/$projectId'
  id:
    | '__root__'
    | '/'
    | '/api/agent'
    | '/dev/effects'
    | '/dev/engine'
    | '/editor/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAgentRoute: typeof ApiAgentRoute
  DevEffectsRoute: typeof DevEffectsRoute
  DevEngineRoute: typeof DevEngineRoute
  EditorProjectIdRoute: typeof EditorProjectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/$projectId': {
      id: '/editor/$projectId'
      path: '/editor/$projectId'
      fullPath: '/editor/$projectId'
      preLoaderRoute: typeof EditorProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/engine': {
      id: '/dev/engine'
      path: '/dev/engine'
      fullPath: '/dev/engine'
      preLoaderRoute: typeof DevEngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/effects': {
      id: '/dev/effects'
      path: '/dev/effects'
      fullPath: '/dev/effects'
      preLoaderRoute: typeof DevEffectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent': {
      id: '/api/agent'
      path: '/api/agent'
      fullPath: '/api/agent'
      preLoaderRoute: typeof ApiAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAgentRoute: ApiAgentRoute,
  DevEffectsRoute: DevEffectsRoute,
  DevEngineRoute: DevEngineRoute,
  EditorProjectIdRoute: EditorProjectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
