/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrandIndexRouteImport } from './routes/brand.index'
import { Route as EditorProjectIdRouteImport } from './routes/editor.$projectId'
import { Route as DevEngineRouteImport } from './routes/dev.engine'
import { Route as DevEffectsRouteImport } from './routes/dev.effects'
import { Route as DevBrandRouteImport } from './routes/dev.brand'
import { Route as DevAnimRouteImport } from './routes/dev.anim'
import { Route as BrandBrandIdRouteImport } from './routes/brand.$brandId'
import { Route as ApiAgentRouteImport } from './routes/api.agent'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandIndexRoute = BrandIndexRouteImport.update({
  id: '/brand/',
  path: '/brand/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorProjectIdRoute = EditorProjectIdRouteImport.update({
  id: '/editor/$projectId',
  path: '/editor/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const DevEngineRoute = DevEngineRouteImport.update({
  id: '/dev/engine',
  path: '/dev/engine',
  getParentRoute: () => rootRouteImport,
} as any)
const DevEffectsRoute = DevEffectsRouteImport.update({
  id: '/dev/effects',
  path: '/dev/effects',
  getParentRoute: () => rootRouteImport,
} as any)
const DevBrandRoute = DevBrandRouteImport.update({
  id: '/dev/brand',
  path: '/dev/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const DevAnimRoute = DevAnimRouteImport.update({
  id: '/dev/anim',
  path: '/dev/anim',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandBrandIdRoute = BrandBrandIdRouteImport.update({
  id: '/brand/$brandId',
  path: '/brand/$brandId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentRoute = ApiAgentRouteImport.update({
  id: '/api/agent',
  path: '/api/agent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/agent': typeof ApiAgentRoute
  '/brand/$brandId': typeof BrandBrandIdRoute
  '/dev/anim': typeof DevAnimRoute
  '/dev/brand': typeof DevBrandRoute
  '/dev/effects': typeof DevEffectsRoute
  '/dev/engine': typeof DevEngineRoute
  '/editor/$projectId': typeof EditorProjectIdRoute
  '/brand/': typeof BrandIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/agent': typeof ApiAgentRoute
  '/brand/$brandId': typeof BrandBrandIdRoute
  '/dev/anim': typeof DevAnimRoute
  '/dev/brand': typeof DevBrandRoute
  '/dev/effects': typeof DevEffectsRoute
  '/dev/engine': typeof DevEngineRoute
  '/editor/$projectId': typeof EditorProjectIdRoute
  '/brand': typeof BrandIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/agent': typeof ApiAgentRoute
  '/brand/$brandId': typeof BrandBrandIdRoute
  '/dev/anim': typeof DevAnimRoute
  '/dev/brand': typeof DevBrandRoute
  '/dev/effects': typeof DevEffectsRoute
  '/dev/engine': typeof DevEngineRoute
  '/editor/$projectId': typeof EditorProjectIdRoute
  '/brand/': typeof BrandIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/agent'
    | '/brand/$brandId'
    | '/dev/anim'
    | '/dev/brand'
    | '/dev/effects'
    | '/dev/engine'
    | '/editor/$projectId'
    | '/brand/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/agent'
    | '/brand/$brandId'
    | '/dev/anim'
    | '/dev/brand'
    | '/dev/effects'
    | '/dev/engine'
    | '/editor/$projectId'
    | '/brand'
  id:
    | '__root__'
    | '/'
    | '/api/agent'
    | '/brand/$brandId'
    | '/dev/anim'
    | '/dev/brand'
    | '/dev/effects'
    | '/dev/engine'
    | '/editor/$projectId'
    | '/brand/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAgentRoute: typeof ApiAgentRoute
  BrandBrandIdRoute: typeof BrandBrandIdRoute
  DevAnimRoute: typeof DevAnimRoute
  DevBrandRoute: typeof DevBrandRoute
  DevEffectsRoute: typeof DevEffectsRoute
  DevEngineRoute: typeof DevEngineRoute
  EditorProjectIdRoute: typeof EditorProjectIdRoute
  BrandIndexRoute: typeof BrandIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand/': {
      id: '/brand/'
      path: '/brand'
      fullPath: '/brand/'
      preLoaderRoute: typeof BrandIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/$projectId': {
      id: '/editor/$projectId'
      path: '/editor/$projectId'
      fullPath: '/editor/$projectId'
      preLoaderRoute: typeof EditorProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/engine': {
      id: '/dev/engine'
      path: '/dev/engine'
      fullPath: '/dev/engine'
      preLoaderRoute: typeof DevEngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/effects': {
      id: '/dev/effects'
      path: '/dev/effects'
      fullPath: '/dev/effects'
      preLoaderRoute: typeof DevEffectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/brand': {
      id: '/dev/brand'
      path: '/dev/brand'
      fullPath: '/dev/brand'
      preLoaderRoute: typeof DevBrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/anim': {
      id: '/dev/anim'
      path: '/dev/anim'
      fullPath: '/dev/anim'
      preLoaderRoute: typeof DevAnimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand/$brandId': {
      id: '/brand/$brandId'
      path: '/brand/$brandId'
      fullPath: '/brand/$brandId'
      preLoaderRoute: typeof BrandBrandIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent': {
      id: '/api/agent'
      path: '/api/agent'
      fullPath: '/api/agent'
      preLoaderRoute: typeof ApiAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAgentRoute: ApiAgentRoute,
  BrandBrandIdRoute: BrandBrandIdRoute,
  DevAnimRoute: DevAnimRoute,
  DevBrandRoute: DevBrandRoute,
  DevEffectsRoute: DevEffectsRoute,
  DevEngineRoute: DevEngineRoute,
  EditorProjectIdRoute: EditorProjectIdRoute,
  BrandIndexRoute: BrandIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
